#! /bin/sh

### BEGIN INIT INFO
# Provides:          DaS
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: RTMP reverse proxy
# Description:       This script starts and stops
#                    RTMP reverse proxy
### END INIT INFO

# Source function library
. /lib/lsb/init-functions

NAME=das
DESC="RTMP reverse proxy"
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/dasd
PIDFILE=/var/run/$NAME.pid
CFGFILE=/etc/das/das.cfg

test -x $DAEMON || exit 0

# Open files (usually 1024, which is way too small for varnish)
ulimit -n ${NFILES:-131072}

# Ensure we have a PATH
export PATH="${PATH:+$PATH:}/usr/sbin:/usr/bin:/sbin:/bin"

start_das() {
    log_daemon_msg "Starting $DESC" "$NAME"
    output=$(/bin/tempfile -s.varnish)
    if start-stop-daemon \
        --start --quiet --pidfile ${PIDFILE} --exec ${DAEMON} -- -f ${CFGFILE} -p ${PIDFILE} > ${output} 2>&1; then
        log_end_msg 0
    else
        log_end_msg 1
        cat $output
        exit 1
    fi
    rm $output
}

stop_das() {
    log_daemon_msg "Stopping $DESC" "$NAME"
    if start-stop-daemon \
        --stop --quiet --pidfile $PIDFILE --retry 10 \
        --exec $DAEMON; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
}

status_das() {
    status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}"
}

case "$1" in
    start)
        start_das
        ;;
    stop)
        stop_das
        ;;
    status)
        status_das
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        log_success_msg "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
